bestofblocket/conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from bestofblocket.core.views import (
    AdSitemap,
    AdView,
    HomePageView,
    RandomAdView,
    RandomGen3AdView,
    SearchPageView,
    TextTemplateView,
)

from ..core.api import api

sitemaps = {
    "ads": AdSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="index"),
    path("slumpa/gen3/", RandomGen3AdView.as_view(), name="randomgen3"),
    path("slumpa/", RandomAdView.as_view(), name="random"),
    path("search/", SearchPageView.as_view(), name="search"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),
    path("robots.txt", TextTemplateView.as_view(template_name="robots.txt")),
    path("ads.txt", TextTemplateView.as_view(template_name="ads.txt")),
    path("<slug:slug>/", AdView.as_view(), name="ad"),
    path("api/", api.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

bestofblocket/core/models.py
from django.db import models

from bestofblocket.core.utils import unique_slugify


class Ad(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="blocketimages/", blank=True, null=True)
    generation = models.SmallIntegerField(default=0, null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    text = models.TextField(null=True, blank=True)
    link = models.URLField(null=True, blank=True)

    class Meta:
        ordering = ["-pk"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/%s/" % self.slug

    def save(
        self,
        *args,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
    ):
        unique_slugify(self, value=self.title)
        super().save()


class Link(models.Model):
    url = models.URLField()

    def __str__(self):
        return self.url

bestofblocket/core/views.py
from django.contrib.sitemaps import Sitemap
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, TemplateView

from bestofblocket.core.models import Ad


class HomePageView(ListView):
    """
    Render index page.
    """

    template_name = "index.html"
    paginate_by = 10
    queryset = Ad.objects.filter(is_approved=True)


class AdView(DetailView):
    """
    Shows one ad.
    """

    model = Ad

    def get_template_names(self):
        return "ad.html"


class RandomAdView(RedirectView):
    """
    Redirects to a random ad.
    """

    permanent = False

    def get_redirect_url(self, **kwargs):
        ad = Ad.objects.filter(is_approved=True).order_by("?")[0]
        return reverse("ad", args=(ad.slug,))


class SearchPageView(ListView):
    """
    Shows search results.
    """

    template_name = "search.html"
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Ad.objects.filter(is_approved=True, title__icontains=query)
        return Ad.objects.filter(is_approved=True)


class RandomGen3AdView(RedirectView):
    """
    Redirect to a random generation 3 (mobile optimized) ad.
    """

    permanent = False

    def get_redirect_url(self, **kwargs):
        ad = Ad.objects.filter(is_approved=True, generation=3).order_by("?")[0]
        return reverse("ad", args=(ad.slug,))


class TextTemplateView(TemplateView):
    """
    Returns text. Used in robots.txt.
    """

    def render_to_response(self, context, **response_kwargs):
        response_kwargs["content_type"] = "text/plain"
        return super(TemplateView, self).render_to_response(context, **response_kwargs)


class AdSitemap(Sitemap):
    """
    Sitemap with all the Ads.
    """

    changefreq = "never"
    priority = 0.5

    def items(self):
        return Ad.objects.filter(is_approved=True)

    def lastmod(self, obj):
        return obj.date

bestofblocket/templates/ad.html
{% extends "base.html" %}
{% block title %} {{ ad.title }} - Best of blocket {% endblock title %}
{% block content %}
<article class="border border-gray-200 border-y-2 md:border-2 p-6 m-4 w-full max-w-3xl md:rounded-lg md:shadow-lg">
    {% if ad.generation == 3 %}
    <h1 class="text-4xl mb-6">
        <a href="{% url 'ad' ad.slug %}" title="{{ ad.title }}"
            >{{ ad.title }}</a
        >
    </h1>
    {% endif %}
    <div class="mb-4">
        {% if ad.image %}
        <a href="{% url 'ad' ad.slug %}" title="{{ ad.title }}">
            <img
                src="{{ ad.image.url }}"
                alt="{{ ad.title }}"
                class="object-cover w-full rounded-md"
            />
        </a>
        {% endif %}
    </div>
    {% if ad.generation == 3 %}
    <p class="text-lg">{{ ad.text|linebreaksbr }}</p>
    {% endif %}
</article>

<a
    href="{% url 'randomgen3' %}"
    class="border border-gray-200 border-y-2 sm:border-2 p-6 m-4 w-full max-w-3xl sm:rounded-lg sm:shadow-lg text-center"
    >Slumpa ny annons</a
>
{% endblock content %}

bestofblocket/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block extrameta %}{% endblock extrameta %}
        <title>{% block title %}Best of blocket{% endblock title %}</title>
        <link rel="stylesheet" href="{% static 'css/output.css' %}" />
        {% block extrajs %}{% endblock extrajs %}
        <script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4932792919894537"
            crossorigin="anonymous"
        ></script>
        <script
            async
            src="https://www.googletagmanager.com/gtag/js?id=G-8EL0TJ0805"
        ></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag() {
                dataLayer.push(arguments);
            }
            gtag("js", new Date());
            gtag("config", "G-8EL0TJ0805");
        </script>
    </head>
    <body>
        <div class="container mx-auto">
            <header class="flex flex-col justify-center items-center pt-4">
                <a href="/" title="Bestofblocket.se"><img src="{% static 'img/logotype.png' %}" alt="Bestofblocket" /></a>
            </header>
            <section class="flex flex-col justify-center items-center m-4">
                <form action="/search/" method="get" class="flex w-full max-w-3xl">
                    <input name="q" type="search" value="{{ request.GET.q }}" placeholder="Sök" class="border border-gray-200 md:border-2 md:border-r-0 border-r-0 p-6 m-0 flex-1 rounded-l-lg md:rounded-l-lg" />
                    <button type="submit" class="border border-blue-500 border-l-0 md:border-2 p-6 m-0 bg-blue-500 text-white rounded-r-lg md:rounded-r-lg cursor-pointer">Sök</button>
                </form>
            </section>
            <main class="flex flex-col justify-center items-center">
                {% block content %}{% endblock content %}
            </main>
        </div>
    </body>
</html>

bestofblocket/templates/index.html
{% extends "base.html" %} {% block content %} {% for ad in ad_list %}
<article class="border border-gray-200 border-y-2 md:border-2 p-6 m-4 w-full max-w-3xl md:rounded-lg md:shadow-lg">
    {% if ad.generation == 3 %}
    <h1 class="text-4xl mb-6">
        <a href="{% url 'ad' ad.slug %}" title="{{ ad.title }}"
            >{{ ad.title }}</a
        >
    </h1>
    {% endif %}
    <div class="mb-4">
        {% if ad.image %}
        <a href="{% url 'ad' ad.slug %}" title="{{ ad.title }}">
            <img
                src="{{ ad.image.url }}"
                alt="{{ ad.title }}"
                class="object-cover w-full rounded-md"
            />
        </a>
        {% endif %}
    </div>
    {% if ad.generation == 3 %}
    <p class="text-lg">{{ ad.text|linebreaksbr }}</p>
    {% endif %}
</article>
{% if forloop.last %} {% if page_obj.has_next %}
<a
    <a href="?page={{ page_obj.next_page_number }}"
    class="border border-gray-200 border-y-2 sm:border-2 p-6 m-4 w-full max-w-3xl sm:rounded-lg sm:shadow-lg text-center"
    >Nästa sida</a
>
{% endif %} {% endif %} {% endfor %} {% endblock content %}

bestofblocket/templates/mobile.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example with a side menu that hides on mobile, just like the Pure website.">

    <title>Best of blocket</title>

    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/side-menu4.css' %}">

    <script src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/ui11.js' %}"></script>
</head>
<body>

<div id="layout">

    <div id="main">
        <div class="header clearfix">
            <span class="title">Best of Blocket</span>
            <div class="navigation">
              <a class="btn next">></a>
            </div>
        </div>

        <div class="content">
            <div id="owl-demo" class="owl-carousel"></div>
        </div>
        <div id="footer" class="clearfix">
          <div id="bottomad">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Bestofblocket Responsive -->
            <ins class="adsbygoogle bestofblocket-responsive"
                 style="display:inline-block"
                 data-ad-client="ca-pub-4932792919894537"
                 data-ad-slot="7556839374"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>
</div>

</body>
</html>

bestofblocket/templates/search.html
{% extends "base.html" %}

{% block content %}
    {% if object_list %}
        {% for ad in object_list %}
            <article class="border border-gray-200 border-y-2 md:border-2 p-6 m-4 w-full max-w-3xl md:rounded-lg md:shadow-lg">
                {% if ad.generation == 3 %}
                    <h1 class="text-4xl mb-6">
                        <a href="{% url 'ad' ad.slug %}" title="{{ ad.title }}">{{ ad.title }}</a>
                    </h1>
                {% endif %}
                <div class="mb-4">
                    {% if ad.image %}
                        <a href="{% url 'ad' ad.slug %}" title="{{ ad.title }}">
                            <img src="{{ ad.image.url }}" alt="{{ ad.title }}" class="object-cover w-full rounded-md" />
                        </a>
                    {% endif %}
                </div>
                {% if ad.generation == 3 %}
                    <p class="text-lg">{{ ad.text|linebreaksbr }}</p>
                {% endif %}
            </article>
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}"
               class="border border-gray-200 border-y-2 sm:border-2 p-6 m-4 w-full max-w-3xl sm:rounded-lg sm:shadow-lg text-center">
                Nästa sida
            </a>
        {% endif %}
    {% else %}
        <p class="mt-4 text-center text-lg">
            Inga sökresultat för "{{ request.GET.q }}".
        </p>
    {% endif %}
{% endblock content %}